import Head from 'next/head';
import Navbar from './navbar';
import Footer from './footer';
import { Inter } from 'next/font/google';
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});
interface Props {
  children: JSX.Element;
}
export default function DefaultLayout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Codercoin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={
          'flex h-full flex-col px-2 text-slate-500 dark:bg-neutral-900 dark:text-slate-400 ' +
          inter.className
        }
      >
        <Navbar />
        <div className="mb-16 mt-24 flex-1 overflow-auto">{children}</div>
        <Footer />
      </main>
    </>
  );
}
