import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import dayjs from 'dayjs';
import 'dayjs/locale/zh-cn';
dayjs.locale('zh-cn');

export default function Home() {
  return (
    <>
      <Head>
        <title>Codercoin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Welcome to Codercoin:
            <code className={styles.code}>http://codercoin.top</code>
          </p>
        </div>

        <div className="flex text-center">
          备案中-{dayjs().format('YYYY-MM-DD H:mm dddd')}
        </div>
      </main>
    </>
  );
}
