import Head from 'next/head';
import Navbar from './layout/navbar';
import Body from './layout/body';
import Footer from './layout/footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>硬币小屋</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-[100vh] flex-col bg-slate-50 dark:bg-gray-800">
        <Navbar />
        <Body />
        <Footer />
      </main>
    </>
  );
}
